### ISSUE TITLE
Empatica API sometimes reporting that a device is not allowed

### ISSUE THREAD

**Issue by sboettcher** [RADAR-CNS/RADAR-Android-Empatica#6]
The callback [here](https://github.com/RADAR-CNS/RADAR-Android-Empatica/blob/dev/src/main/java/org/radarcns/empatica/E4DeviceManager.java#L150) sometimes sometimes just does not return allowed as true, even if an internet connection is available and the same device has been successfully connected just a minute before.
I don't think we can really change that since it is an Empatica SDK provided value, but wanted to report it anyway. Maybe we can contact Empatica again and see if we can get this debugged/resolved sometime.

Edit: also I then get repeated toasts from the app "Cannot connect to device Empatica E4 - 000084"

Edit2: and when I then switch off the E4 and switch it on again, the LED is green for 1-2 sec, then white for 1-2 sec, the it switches off and when I turn it on again it can connect normally...

**Comment by blootsvoets** [comment]
Good point, yes, sometimes a Empatica device changes its device names between connections. Eventually, it does revert to the original device name though. An alternative would be to filter not on the name but on the MAC-address: that should stay the same. The logs lists it in a message like
```
Bluetooth address: 00:11:22:33:44:55
```
It might also be listed with the documentation... I believe the device name is derived from the last 6 characters in the mac-address though, so it could be that that address also changes. In any case, we don't have any control over the device name, but the MAC-address is the bluetooth address that was detected by Android. Still, I'm not sure if the watch always reports the same MAC-address.

**Comment by sboettcher** [comment]
I have entered only MAC address in the filter from the start, already thought this might be the surest way of filtering.

**Comment by sboettcher** [comment]
BTW I have updated all or E4s to the newest firmware now, maybe there are some problems with that after all...

**Comment by sboettcher** [comment]
>  I believe the device name is derived from the last 6 characters in the mac-address though, so it could be that that address also changes. In any case, we don't have any control over the device name, but the MAC-address is the bluetooth address that was detected by Android. Still, I'm not sure if the watch always reports the same MAC-address.

As far as I have seen it always reports the same MAC, and it is indeed derived from the device ID (NOT the etched S/N on the back of the devices) in a pattern where an ID aabbcc corresponds to MAC 00:07:80:CC:BB:AA
at least for all 14 of our working devices that is the case

**Comment by blootsvoets** [comment]
So I've seen a few times that at least the device name is different between connection attempts. If it is indeed directly derived from the MAC-address, then the MAC-address should also be different sometimes. It's something to check with Empatica. This was the case with the older firmware at least. As long as it does connect in a later attempt, at least the setup is working?

**Comment by sboettcher** [comment]
Yeah, it is just a nuisance at the moment. Just now I also had the case that it wold have this problem, then after 20sec or so it still connected anyway.

**Comment by sboettcher** [comment]
I also added a warning log in the last else in that didDiscoverDevice()

When this happens I get log like this over and over:
```
08-01 13:49:01.263 12538-12538/org.radarcns.android.android I/E4DeviceManager: Bluetooth address: 00:07:80:1F:18:78
08-01 13:49:01.263 12538-12538/org.radarcns.android.android W/E4DeviceManager: Device Empatica E4 - 000084 with address 00:07:80:1F:18:78 is not an allowed device.
```
So at least the API seems to report the correct MAC in these cases, but the ID is not the correct one and it is also always 000084 no matter what E4 is used. Looks to me like an internal error state or something, probably nothing we can handle ourselves.

**Comment by blootsvoets** [comment]
Ah OK, yes indeed. Their API pass the `allowed` flag to didDiscoverDevice, if that is true, it should not throw that exception, but apparently it does. Strange...

**Comment by sboettcher** [comment]
Sorry that was a missclick.
Well it does not throw an exception, it just rejects the device over and over. Let's see what Empatica's ideas are concerning this.

**Comment by sboettcher** [comment]
Closing, since it looks like this can't be fixed by us. Solved by powercycling the E4, upon which it will always reset (white LED), which to me indicates a firmware issue.
