### ISSUE TITLE
Empatica sometimes loses BT connection

### ISSUE THREAD

**Issue by sboettcher** [RADAR-CNS/RADAR-Android-Empatica#8]
I am just opening this issue to gather some logs and maybe share ideas of why this happens.
Some adb logs I have managed to recover, from points in time where a connection was lost:

<details>
<summary>Log 1</summary>
<pre><code>
B3_logs:202736:08-23 14:39:57.471  1942 15541 I o*.r*.a*.d*.TapeCache: Trying to retrieve records from topic android_biovotion_battery_state
B3_logs:202737:08-23 14:39:57.473  1942 15541 I o*.r*.a*.d*.TapeCache: Trying to retrieve records from topic android_biovotion_heart_rate_variability
B3_logs:202738:08-23 14:39:57.475  1942 15541 I o*.r*.a*.d*.TapeCache: Trying to retrieve records from topic android_biovotion_ppg_raw
B3_logs:202739:08-23 14:39:57.653  7792  7815 W bt_btif : bta_gattc_conn_cback() - cif=3 connected=0 conn_id=3 reason=0x0008
B3_logs:202740:08-23 14:39:57.654  7792  7815 W bt_btif : bta_gattc_conn_cback() - cif=4 connected=0 conn_id=4 reason=0x0008
B3_logs:202741:08-23 14:39:57.654  7792  7815 W bt_btif : bta_gattc_conn_cback() - cif=5 connected=0 conn_id=5 reason=0x0008
B3_logs:202742:08-23 14:39:57.654  7792  7815 W bt_btif : bta_gattc_conn_cback() - cif=7 connected=0 conn_id=7 reason=0x0008
B3_logs:202743:08-23 14:39:57.654  7792  7815 I bt_btm_sec: btm_sec_disconnected clearing pending flag handle:1025 reason:8
B3_logs:202744:08-23 14:39:57.656  7792  7808 D BtGatt.GattService: onDisconnected() - clientIf=7, connId=7, address=00:07:80:F2:1A:3E
B3_logs:202745:08-23 14:39:57.659  1942  1956 D BluetoothGatt: onClientConnectionState() - status=8 clientIf=7 device=00:07:80:F2:1A:3E
B3_logs:202746:08-23 14:39:57.660  1942  1956 I E4DeviceManager: Updated E4 status to DISCONNECTED
B3_logs:202747:08-23 14:39:57.674  1942  1942 I DeviceServiceConnection: Device status changed of device Empatica E4 - 3e1af2
B3_logs:202748:08-23 14:39:57.674  1942  1942 I DeviceServiceConnection: Updated device status to DISCONNECTED
B3_logs:202749:08-23 14:39:57.684  1046  1694 I NotificationService: cancelToast pkg=org.radarcns.android.android callback=android.app.ITransientNotification$Stub$Proxy@9960c94
B3_logs:202750:08-23 14:39:57.684  1046  1694 W NotificationService: Toast already cancelled. pkg=org.radarcns.android.android callback=android.app.ITransientNotification$Stub$Proxy@9960c94
B3_logs:202751:08-23 14:39:57.696  1942  1956 I E4DeviceManager: Closing device Empatica E4 - 3e1af2
B3_logs:202752:08-23 14:39:57.700  1942 12156 I E4DeviceManager: Initiated device Empatica E4 - 3e1af2 stop-sequence
B3_logs:202753:08-23 14:39:57.701  7792  7802 E BtGatt.GattService: writeCharacteristic() - No connection for 00:07:80:F2:1A:3E...
B3_logs:202754:08-23 14:39:57.702  1942 12156 D BluetoothGatt: cancelOpen() - device: 00:07:80:F2:1A:3E
B3_logs:202755:08-23 14:39:57.702  7792  7830 D BtGatt.GattService: clientDisconnect() - address=00:07:80:F2:1A:3E, connId=null
B3_logs:202756:08-23 14:39:57.703  1942 12156 I E4DeviceManager: Updated E4 status to DISCONNECTED
B3_logs:202757:08-23 14:39:57.703  1942 12156 I E4DeviceManager: Cleaning up device manager
B3_logs:202758:08-23 14:39:57.705  1942 12156 I E4DeviceManager: Cleaned up device manager
B3_logs:202759:08-23 14:39:57.705  1942 12156 I E4DeviceManager: Finished device Empatica E4 - 3e1af2 stop-sequence
B3_logs:202760:08-23 14:39:57.711  1942  1956 D EmpaDeviceManager: HnU - 4
B3_logs:202761:08-23 14:39:57.722  1942  1956 D EmpaDeviceManager: Good Sessions: 4
B3_logs:202762:08-23 14:39:57.731  7792  7808 E BluetoothRemoteDevices: state12newState1
B3_logs:202763:08-23 14:39:57.733  1942  1942 I o*.r*.a*.MainActivity: Starting recording on connection DeviceServiceConnection<org.radarcns.empatica.E4Service>
B3_logs:202764:08-23 14:39:57.733  1942  1942 I DeviceService: Starting recording
B3_logs:202765:08-23 14:39:57.733  1942  1942 I E4DeviceManager: Starting scanning
B3_logs:202766:08-23 14:39:57.737  7792  7792 D BluetoothMapService: onReceive
B3_logs:202767:08-23 14:39:57.737  7792  7792 D BluetoothMapService: onReceive: android.bluetooth.device.action.ACL_DISCONNECTED
B3_logs:202768:08-23 14:39:57.745  1678  1678 V BluetoothDiscoveryReceiver: Received: android.bluetooth.adapter.action.DISCOVERY_STARTED
B3_logs:202769:08-23 14:39:57.746  7792  7815 E bt_btif : No such connection need to be cancelled
B3_logs:202770:08-23 14:39:57.746  7792  7815 E bt_btif : bta_gattc_mark_bg_conn unable to find the bg connection mask for: 00:07:80:f2:1a:3e
B3_logs:202771:08-23 14:39:57.755  1942  1942 I o*.r*.a*.MainActivity: Starting recording on connection DeviceServiceConnection<org.radarcns.biovotion.BiovotionService>
B3_logs:202772:08-23 14:39:57.756  1942  1942 D BluetoothGatt: close()
B3_logs:202773:08-23 14:39:57.756  1942  1942 D BluetoothGatt: unregisterApp() - mClientIf=7
B3_logs:202774:08-23 14:39:57.757  7792  7802 D BtGatt.GattService: unregisterClient() - clientIf=7
B3_logs:202775:08-23 14:39:57.761  1942 15586 I E4DeviceManager: Creating EmpaDeviceManager
B3_logs:202776:08-23 14:39:57.768  1942 15586 I E4DeviceManager: Updated E4 status to DISCONNECTED
B3_logs:202777:08-23 14:39:57.777  1942 15586 I E4DeviceManager: Authenticating EmpaDeviceManager
B3_logs:202778:08-23 14:39:57.777  1942 15586 I E4DeviceManager: Authenticated EmpaDeviceManager
B3_logs:202779:08-23 14:39:57.778  7792  7801 I art     : Background sticky concurrent mark sweep GC freed 32229(1251KB) AllocSpace objects, 0(0B) LOS objects, 38% free, 2MB/3MB, paused 9.245ms total 39.341ms
B3_logs:202780:08-23 14:39:57.811   147   178 E BufferQueueProducer: [Toast] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
B3_logs:202781:08-23 14:39:57.826  1942  8050 I o*.r*.e*.EEGSyncManager: EEG sync sending 10ms pulse after a delay of 1028ms.
B3_logs:202782:08-23 14:39:57.837  1942  8050 I o*.r*.e*.EEGSyncManager: EEG sync pulse sent.
B3_logs:202783:08-23 14:39:58.579  1942  2073 I o*.r*.a*.d*.TapeCache: Removing data from topic application_record_counts at offset 9097 onwards (1 records)
B3_logs:202784:08-23 14:39:58.597  1942  8050 I o*.r*.e*.EEGSyncManager: EEG sync sending 10ms pulse after a delay of 760ms.
B3_logs:202785:08-23 14:39:58.608  1942  8050 I o*.r*.e*.EEGSyncManager: EEG sync pulse sent.
B3_logs:202786:08-23 14:39:58.816  1942 15585 W EmpaDeviceManager: USMDC failed
B3_logs:202787:08-23 14:39:58.822  1942 15589 E DeviceLabelHandler: Error downloading label file
B3_logs:202788:08-23 14:39:58.949  1942  1942 I E4DeviceManager: Updated E4 status to READY
B3_logs:202789:08-23 14:39:58.962  1942 15586 D BluetoothAdapter: startLeScan(): null
B3_logs:202790:08-23 14:39:58.964  1942 15586 D BluetoothAdapter: STATE_ON
B3_logs:202791:08-23 14:39:58.967  7792  7830 D BtGatt.GattService: registerClient() - UUID=669f1b52-7e3b-4eae-9aa4-940cd7283d9d
B3_logs:202792:08-23 14:39:58.968  7792  7808 D BtGatt.GattService: onClientRegistered() - UUID=669f1b52-7e3b-4eae-9aa4-940cd7283d9d, clientIf=6
B3_logs:202793:08-23 14:39:58.968  1942  2113 D BluetoothLeScanner: onClientRegistered() - status=0 clientIf=6
B3_logs:202794:08-23 14:39:58.969  7792  7803 D BtGatt.GattService: start scan with filters
B3_logs:202795:08-23 14:39:58.973  7792  7811 D BtGatt.ScanManager: handling starting scan
B3_logs:202796:08-23 14:39:58.976  7792  7811 D BtGatt.ScanManager: configureRegularScanParams() - queue=2
B3_logs:202797:08-23 14:39:58.976  7792  7811 D BtGatt.ScanManager: configureRegularScanParams() - ScanSetting Scan mode=2 mLastConfiguredScanSetting=2
B3_logs:202798:08-23 14:39:58.977  1942 15586 I E4DeviceManager: Started scanning
B3_logs:202799:08-23 14:39:58.981  1942  1942 I DeviceServiceConnection: Device status changed of device UDOONEO-MX6SX
B3_logs:202800:08-23 14:39:58.981  1942  1942 I DeviceServiceConnection: Updated device status to READY
B3_logs:202801:08-23 14:39:58.983  1046 10820 I NotificationService: cancelToast pkg=org.radarcns.android.android callback=android.app.ITransientNotification$Stub$Proxy@e87a47e
B3_logs:202802:08-23 14:39:59.037   147   176 E BufferQueueProducer: [Toast] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
B3_logs:202803:08-23 14:39:59.302  1942  2092 I o*.r*.a*.d*.TapeCache: Writing 8 records to file in topic android_empatica_e4_temperature
B3_logs:202804:08-23 14:39:59.434  1942  2073 I o*.r*.a*.d*.TapeCache: Removed data from topic application_record_counts at offset 9097 onwards (1 records)
B3_logs:202805:08-23 14:39:59.451  1942 15538 I TableDataHandler:                     application_record_counts uploaded    1 records
B3_logs:202806:08-23 14:39:59.451  1942 15538 I o*.r*.a*.d*.TapeCache: Trying to retrieve records from topic application_uptime
B3_logs:202807:08-23 14:39:59.517  1942  2096 I o*.r*.a*.d*.TapeCache: Removing data from topic android_eeg_sync_pulse at offset 179665 onwards (6 records)
B3_logs:202808:08-23 14:39:59.538  1942  2073 I o*.r*.a*.d*.TapeCache: Removing data from topic application_uptime at offset 9097 onwards (1 records)
</code></pre>
</details>

<details>
<summary>Log 2</summary>
<pre><code>
B1_logs:12299:08-22 20:49:26.461  1928 11173 I chatty  : uid=10045(org.radarcns.android.android) expire 17 lines
B1_logs:12300:08-22 20:49:26.476  1928 11174 I chatty  : uid=10045(org.radarcns.android.android) expire 9 lines
B1_logs:12301:08-22 20:49:32.249  1727  2007 W bt_btif : bta_gattc_conn_cback() - cif=3 connected=0 conn_id=3 reason=0x0008
B1_logs:12302:08-22 20:49:32.249  1727  2007 W bt_btif : bta_gattc_conn_cback() - cif=4 connected=0 conn_id=4 reason=0x0008
B1_logs:12303:08-22 20:49:32.249  1727  2007 W bt_btif : bta_gattc_conn_cback() - cif=5 connected=0 conn_id=5 reason=0x0008
B1_logs:12304:08-22 20:49:32.249  1727  2007 W bt_btif : bta_gattc_conn_cback() - cif=7 connected=0 conn_id=7 reason=0x0008
B1_logs:12305:08-22 20:49:32.249  1727  2007 I bt_btm_sec: btm_sec_disconnected clearing pending flag handle:1025 reason:8
B1_logs:12306:08-22 20:49:32.250  1727  1800 D BtGatt.GattService: onDisconnected() - clientIf=7, connId=7, address=00:07:80:1F:18:78
B1_logs:12307:08-22 20:49:32.253  1928  3272 I chatty  : uid=10045(org.radarcns.android.android) Binder_4 expire 5 lines
B1_logs:12308:08-22 20:49:32.262  1928 11097 I chatty  : uid=10045(org.radarcns.android.android) expire 6 lines
B1_logs:12309:08-22 20:49:32.269  1727  1769 E BtGatt.GattService: writeCharacteristic() - No connection for 00:07:80:1F:18:78...
B1_logs:12310:08-22 20:49:32.270  1727  1766 D BtGatt.GattService: clientDisconnect() - address=00:07:80:1F:18:78, connId=null
B1_logs:12311:08-22 20:49:32.283  1928  1928 I chatty  : uid=10045(org.radarcns.android.android) expire 13 lines
B1_logs:12312:08-22 20:49:32.293  1727  1800 E BluetoothRemoteDevices: state12newState1
B1_logs:12313:08-22 20:49:32.300  1727  1727 D BluetoothMapService: onReceive
B1_logs:12314:08-22 20:49:32.301  1727  1727 D BluetoothMapService: onReceive: android.bluetooth.device.action.ACL_DISCONNECTED
B1_logs:12315:08-22 20:49:32.310  1727  2007 E bt_btif : No such connection need to be cancelled
B1_logs:12316:08-22 20:49:32.311  1727  2007 E bt_btif : bta_gattc_mark_bg_conn unable to find the bg connection mask for: 00:07:80:1f:18:78
B1_logs:12317:08-22 20:49:32.321  1046  1057 I NotificationService: cancelToast pkg=org.radarcns.android.android callback=android.app.ITransientNotification$Stub$Proxy@a0aeb5b
B1_logs:12318:08-22 20:49:32.321  1046  1057 W NotificationService: Toast already cancelled. pkg=org.radarcns.android.android callback=android.app.ITransientNotification$Stub$Proxy@a0aeb5b
B1_logs:12319:08-22 20:49:32.333  1928  2059 I chatty  : uid=10045(org.radarcns.android.android) TableDataHandle expire 9 lines
B1_logs:12320:08-22 20:49:32.341  1727  2013 D BtGatt.GattService: unregisterClient() - clientIf=7
B1_logs:12321:08-22 20:49:32.345  1928 11229 I chatty  : uid=10045(org.radarcns.android.android) expire 7 lines
B1_logs:12322:08-22 20:49:32.368  1928 11175 I chatty  : uid=10045(org.radarcns.android.android) expire 18 lines
B1_logs:12323:08-22 20:49:32.386   149  1655 E BufferQueueProducer: [Toast] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
B1_logs:12324:08-22 20:49:32.591  1928 11086 I chatty  : uid=10045(org.radarcns.android.android) expire 11 lines
B1_logs:12325:08-22 20:49:33.118  1928 11231 I chatty  : uid=10045(org.radarcns.android.android) expire 1 line
B1_logs:12326:08-22 20:49:33.119  1928 11227 I chatty  : uid=10045(org.radarcns.android.android) expire 1 line
B1_logs:12327:08-22 20:49:33.289  1727  2076 D BtGatt.GattService: registerClient() - UUID=aba9b7af-919c-4d16-bf86-71f523055713
B1_logs:12328:08-22 20:49:33.290  1727  1800 D BtGatt.GattService: onClientRegistered() - UUID=aba9b7af-919c-4d16-bf86-71f523055713, clientIf=6
B1_logs:12329:08-22 20:49:33.290  1928  2086 I chatty  : uid=10045(org.radarcns.android.android) Binder_3 expire 1 line
B1_logs:12330:08-22 20:49:33.292  1727  2013 D BtGatt.GattService: start scan with filters
B1_logs:12331:08-22 20:49:33.296  1727  1803 D BtGatt.ScanManager: handling starting scan
B1_logs:12332:08-22 20:49:33.299  1727  1803 D BtGatt.ScanManager: configureRegularScanParams() - queue=2
B1_logs:12333:08-22 20:49:33.299  1727  1803 D BtGatt.ScanManager: configureRegularScanParams() - ScanSetting Scan mode=2 mLastConfiguredScanSetting=2
B1_logs:12334:08-22 20:49:33.334  1046  1648 I NotificationService: cancelToast pkg=org.radarcns.android.android callback=android.app.ITransientNotification$Stub$Proxy@fedf50d
B1_logs:12335:08-22 20:49:33.383   149   190 E BufferQueueProducer: [Toast] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
B1_logs:12336:08-22 20:49:36.494  1928 11176 I chatty  : uid=10045(org.radarcns.android.android) expire 48 lines
B1_logs:12337:08-22 20:49:38.777  1928 11086 I chatty  : uid=10045(org.radarcns.android.android) expire 33 lines
</code></pre>
</details>

<details>
<summary>Log 3</summary>
<pre><code>
logs/B2_logs_2:158074:08-24 16:06:57.643  1949  2063 I o*.r*.a*.d*.TapeCache: Removing data from topic android_eeg_sync_pulse at offset 270558 onwards (6 records)
logs/B2_logs_2:158075:08-24 16:06:57.649  1949  2057 I o*.r*.a*.d*.TapeCache: Removing data from topic android_empatica_e4_temperature at offset 759615 onwards (16 records)
logs/B2_logs_2:158076:08-24 16:06:57.667  1949  2063 I o*.r*.a*.d*.TapeCache: Removed data from topic android_eeg_sync_pulse at offset 270558 onwards (6 records)
logs/B2_logs_2:158077:08-24 16:06:57.668  1949  2057 I o*.r*.a*.d*.TapeCache: Removed data from topic android_empatica_e4_temperature at offset 759615 onwards (16 records)
logs/B2_logs_2:158078:08-24 16:06:57.689  1949 23861 I TableDataHandler:               android_empatica_e4_temperature uploaded   16 records
logs/B2_logs_2:158079:08-24 16:06:57.689  1949 23861 I o*.r*.a*.d*.TapeCache: Trying to retrieve records from topic android_empatica_e4_acceleration
logs/B2_logs_2:158080:08-24 16:06:57.692  1949 23863 I TableDataHandler:                        android_eeg_sync_pulse uploaded    6 records
logs/B2_logs_2:158081:08-24 16:06:57.782  1729  2028 W bt_btif : bta_gattc_conn_cback() - cif=3 connected=0 conn_id=3 reason=0x0008
logs/B2_logs_2:158082:08-24 16:06:57.782  1729  2028 W bt_btif : bta_gattc_conn_cback() - cif=4 connected=0 conn_id=4 reason=0x0008
logs/B2_logs_2:158083:08-24 16:06:57.782  1729  2028 W bt_btif : bta_gattc_conn_cback() - cif=5 connected=0 conn_id=5 reason=0x0008
logs/B2_logs_2:158084:08-24 16:06:57.782  1729  2028 W bt_btif : bta_gattc_conn_cback() - cif=7 connected=0 conn_id=7 reason=0x0008
logs/B2_logs_2:158085:08-24 16:06:57.782  1729  2028 I bt_btm_sec: btm_sec_disconnected clearing pending flag handle:1025 reason:8
logs/B2_logs_2:158086:08-24 16:06:57.783  1729  1798 D BtGatt.GattService: onDisconnected() - clientIf=7, connId=7, address=00:07:80:F2:1C:2F
logs/B2_logs_2:158087:08-24 16:06:57.789  1949  1961 D BluetoothGatt: onClientConnectionState() - status=8 clientIf=7 device=00:07:80:F2:1C:2F
logs/B2_logs_2:158088:08-24 16:06:57.789  1949  1961 I E4DeviceManager: Updated E4 status to DISCONNECTED
logs/B2_logs_2:158089:08-24 16:06:57.793  1949  1949 I DeviceServiceConnection: Device status changed of device Empatica E4 - 2f1cf2
logs/B2_logs_2:158090:08-24 16:06:57.793  1949  1949 I DeviceServiceConnection: Updated device status to DISCONNECTED
logs/B2_logs_2:158091:08-24 16:06:57.799  1949  1961 I E4DeviceManager: Closing device Empatica E4 - 2f1cf2
logs/B2_logs_2:158092:08-24 16:06:57.800  1949 21737 I E4DeviceManager: Initiated device Empatica E4 - 2f1cf2 stop-sequence
logs/B2_logs_2:158093:08-24 16:06:57.801  1729  1773 E BtGatt.GattService: writeCharacteristic() - No connection for 00:07:80:F2:1C:2F...
logs/B2_logs_2:158094:08-24 16:06:57.801  1949 21737 D BluetoothGatt: cancelOpen() - device: 00:07:80:F2:1C:2F
logs/B2_logs_2:158095:08-24 16:06:57.802  1729  2102 D BtGatt.GattService: clientDisconnect() - address=00:07:80:F2:1C:2F, connId=null
logs/B2_logs_2:158096:08-24 16:06:57.803  1949 21737 I E4DeviceManager: Updated E4 status to DISCONNECTED
logs/B2_logs_2:158097:08-24 16:06:57.803  1949 21737 I E4DeviceManager: Cleaning up device manager
logs/B2_logs_2:158098:08-24 16:06:57.804  1949 21737 I E4DeviceManager: Cleaned up device manager
logs/B2_logs_2:158099:08-24 16:06:57.804  1949 21737 I E4DeviceManager: Finished device Empatica E4 - 2f1cf2 stop-sequence
logs/B2_logs_2:158100:08-24 16:06:57.806  1949  1961 D EmpaDeviceManager: HnU - 8
logs/B2_logs_2:158101:08-24 16:06:57.807  1949  1961 D EmpaDeviceManager: Good Sessions: 8
logs/B2_logs_2:158102:08-24 16:06:57.818  1047  1652 I NotificationService: cancelToast pkg=org.radarcns.android.android callback=android.app.ITransientNotification$Stub$Proxy@7dcf3aa
logs/B2_logs_2:158103:08-24 16:06:57.818  1047  1652 W NotificationService: Toast already cancelled. pkg=org.radarcns.android.android callback=android.app.ITransientNotification$Stub$Proxy@7dcf3aa
logs/B2_logs_2:158104:08-24 16:06:57.819  1729  1798 E BluetoothRemoteDevices: state12newState1
logs/B2_logs_2:158105:08-24 16:06:57.823  1729  1729 D BluetoothMapService: onReceive
logs/B2_logs_2:158106:08-24 16:06:57.823  1729  1729 D BluetoothMapService: onReceive: android.bluetooth.device.action.ACL_DISCONNECTED
logs/B2_logs_2:158107:08-24 16:06:57.829  1729  2028 E bt_btif : No such connection need to be cancelled
logs/B2_logs_2:158108:08-24 16:06:57.830  1729  2028 E bt_btif : bta_gattc_mark_bg_conn unable to find the bg connection mask for: 00:07:80:f2:1c:2f
logs/B2_logs_2:158109:08-24 16:06:57.834  1949  1949 I o*.r*.a*.MainActivity: Starting recording on connection DeviceServiceConnection<org.radarcns.empatica.E4Service>
logs/B2_logs_2:158110:08-24 16:06:57.834  1949  1949 I DeviceService: Starting recording
logs/B2_logs_2:158111:08-24 16:06:57.834  1949  1949 I E4DeviceManager: Starting scanning
logs/B2_logs_2:158112:08-24 16:06:57.840  1949  1949 I o*.r*.a*.MainActivity: Starting recording on connection DeviceServiceConnection<org.radarcns.biovotion.BiovotionService>
logs/B2_logs_2:158113:08-24 16:06:57.840  1949  1949 D BluetoothGatt: close()
logs/B2_logs_2:158114:08-24 16:06:57.841  1949  1949 D BluetoothGatt: unregisterApp() - mClientIf=7
logs/B2_logs_2:158115:08-24 16:06:57.841  1729  2102 D BtGatt.GattService: unregisterClient() - clientIf=7
logs/B2_logs_2:158116:08-24 16:06:57.843  1949 23909 I E4DeviceManager: Creating EmpaDeviceManager
logs/B2_logs_2:158117:08-24 16:06:57.847  1949 23909 I E4DeviceManager: Updated E4 status to DISCONNECTED
logs/B2_logs_2:158118:08-24 16:06:57.854  1949 21736 I *plicationStatusManager: Updating application status
logs/B2_logs_2:158119:08-24 16:06:57.865  1949 23909 I E4DeviceManager: Authenticating EmpaDeviceManager
logs/B2_logs_2:158120:08-24 16:06:57.866  1949 23909 I E4DeviceManager: Authenticated EmpaDeviceManager
logs/B2_logs_2:158121:08-24 16:06:57.866  1949 21736 I *plicationStatusManager: Server Status: CONNECTED; Device IP: 10.195.50.240
logs/B2_logs_2:158122:08-24 16:06:57.866  1949 21736 I *plicationStatusManager: Number of records: {sent: 2500154, unsent: 87, cached: 87}
logs/B2_logs_2:158123:08-24 16:06:57.897   151   181 E BufferQueueProducer: [Toast] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
logs/B2_logs_2:158124:08-24 16:06:57.905  1949  1949 I o*.r*.DeviceRowView: Device status is DISCONNECTED
logs/B2_logs_2:158125:08-24 16:06:58.325  1949  2057 I o*.r*.a*.d*.TapeCache: Writing 33 records to file in topic android_empatica_e4_blood_volume_pulse
logs/B2_logs_2:158126:08-24 16:06:58.403  1949  2057 I o*.r*.a*.d*.TapeCache: Removing data from topic android_empatica_e4_acceleration at offset 6093335 onwards (132 records)
logs/B2_logs_2:158127:08-24 16:06:58.417  1949 21738 I o*.r*.e*.EEGSyncManager: EEG sync sending 10ms pulse after a delay of 1292ms.
logs/B2_logs_2:158128:08-24 16:06:58.425  1949  2057 I o*.r*.a*.d*.TapeCache: Removed data from topic android_empatica_e4_acceleration at offset 6093335 onwards (132 records)
logs/B2_logs_2:158129:08-24 16:06:58.428  1949 21738 I o*.r*.e*.EEGSyncManager: EEG sync pulse sent.
logs/B2_logs_2:158130:08-24 16:06:58.437  1949 23861 I TableDataHandler:              android_empatica_e4_acceleration uploaded  132 records
logs/B2_logs_2:158131:08-24 16:06:58.437  1949 23861 I o*.r*.a*.d*.TapeCache: Trying to retrieve records from topic android_empatica_e4_sensor_status
logs/B2_logs_2:158132:08-24 16:06:58.439  1949 23861 I o*.r*.a*.d*.TapeCache: Trying to retrieve records from topic android_empatica_e4_inter_beat_interval
logs/B2_logs_2:158133:08-24 16:06:58.439  1949 23861 I o*.r*.a*.d*.TapeCache: Trying to retrieve records from topic android_empatica_e4_electrodermal_activity
logs/B2_logs_2:158134:08-24 16:06:58.486  1949 23908 W EmpaDeviceManager: USMDC failed
logs/B2_logs_2:158135:08-24 16:06:58.490  1949  2057 I o*.r*.a*.d*.TapeCache: Removing data from topic android_empatica_e4_electrodermal_activity at offset 761627 onwards (24 records)
logs/B2_logs_2:158136:08-24 16:06:58.509  1949  2057 I o*.r*.a*.d*.TapeCache: Removed data from topic android_empatica_e4_electrodermal_activity at offset 761627 onwards (24 records)
logs/B2_logs_2:158137:08-24 16:06:58.514  1949 23861 I TableDataHandler:    android_empatica_e4_electrodermal_activity uploaded   24 records
logs/B2_logs_2:158138:08-24 16:06:58.515  1949 23861 I o*.r*.a*.d*.TapeCache: Trying to retrieve records from topic android_empatica_e4_blood_volume_pulse
logs/B2_logs_2:158139:08-24 16:06:58.599  1949 23912 E DeviceLabelHandler: Error downloading label file
logs/B2_logs_2:158140:08-24 16:06:58.855  1949  2057 I o*.r*.a*.d*.TapeCache: Removing data from topic android_empatica_e4_blood_volume_pulse at offset 12186723 onwards (187 records)
logs/B2_logs_2:158141:08-24 16:06:58.872  1949  1949 I E4DeviceManager: Updated E4 status to READY
logs/B2_logs_2:158142:08-24 16:06:58.881  1949 23909 D BluetoothAdapter: startLeScan(): null
logs/B2_logs_2:158143:08-24 16:06:58.884  1949 23909 D BluetoothAdapter: STATE_ON
logs/B2_logs_2:158144:08-24 16:06:58.887  1729  1779 D BtGatt.GattService: registerClient() - UUID=7931a13f-c531-440e-8c80-b9df62795696
logs/B2_logs_2:158145:08-24 16:06:58.888  1729  1798 D BtGatt.GattService: onClientRegistered() - UUID=7931a13f-c531-440e-8c80-b9df62795696, clientIf=6
logs/B2_logs_2:158146:08-24 16:06:58.888  1949  1961 D BluetoothLeScanner: onClientRegistered() - status=0 clientIf=6
logs/B2_logs_2:158147:08-24 16:06:58.889  1729  2103 D BtGatt.GattService: start scan with filters
logs/B2_logs_2:158148:08-24 16:06:58.893  1729  1801 D BtGatt.ScanManager: handling starting scan
logs/B2_logs_2:158149:08-24 16:06:58.896  1729  1801 D BtGatt.ScanManager: configureRegularScanParams() - queue=2
logs/B2_logs_2:158150:08-24 16:06:58.896  1729  1801 D BtGatt.ScanManager: configureRegularScanParams() - ScanSetting Scan mode=2 mLastConfiguredScanSetting=2
logs/B2_logs_2:158151:08-24 16:06:58.897  1949 23909 I E4DeviceManager: Started scanning
logs/B2_logs_2:158152:08-24 16:06:58.900  1949  1949 I DeviceServiceConnection: Device status changed of device UDOONEO-MX6SX
logs/B2_logs_2:158153:08-24 16:06:58.900  1949  1949 I DeviceServiceConnection: Updated device status to READY
logs/B2_logs_2:158154:08-24 16:06:58.904  1047  1652 I NotificationService: cancelToast pkg=org.radarcns.android.android callback=android.app.ITransientNotification$Stub$Proxy@2eee2e4
logs/B2_logs_2:158155:08-24 16:06:58.924  1949  2057 I o*.r*.a*.d*.TapeCache: Removed data from topic android_empatica_e4_blood_volume_pulse at offset 12186723 onwards (187 records)
logs/B2_logs_2:158156:08-24 16:06:58.935  1949  2063 I o*.r*.a*.d*.TapeCache: Writing 3 records to file in topic android_eeg_sync_pulse
logs/B2_logs_2:158157:08-24 16:06:58.936  1949 23861 I TableDataHandler:        android_empatica_e4_blood_volume_pulse uploaded  187 records
logs/B2_logs_2:158158:08-24 16:06:58.958   151  1609 E BufferQueueProducer: [Toast] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
logs/B2_logs_2:158159:08-24 16:06:58.969  1949  1949 I o*.r*.DeviceRowView: Device status is READY
logs/B2_logs_2:158160:08-24 16:06:59.745  1949 21738 I o*.r*.e*.EEGSyncManager: EEG sync sending 10ms pulse after a delay of 1316ms.
logs/B2_logs_2:158161:08-24 16:06:59.757  1949 21738 I o*.r*.e*.EEGSyncManager: EEG sync pulse sent.
logs/B2_logs_2:158162:08-24 16:07:00.368  1949  2045 I o*.r*.a*.d*.TapeCache: Writing 1 records to file in topic application_server_status
logs/B2_logs_2:158163:08-24 16:07:00.403  1949  2045 I o*.r*.a*.d*.TapeCache: Writing 1 records to file in topic application_uptime
logs/B2_logs_2:158164:08-24 16:07:00.441  1949  2045 I o*.r*.a*.d*.TapeCache: Writing 1 records to file in topic application_record_counts
</code></pre>
</details>

I have no idea why adb decided to prune the pRMT logs in the second case. I also don't know if the actual cause for both disconnections was the same, only that the symptom (disconnected E4) was the same. In all cases the E4 battery was far from empty (around 40-60%).

**Comment by afolarin** [comment]
Curious if this is an Android/UDOO or Empatica problem
We;ve had this reported (at least twice now), maybe move to the issue pRMT?

![img-20171106-wa0001](https://user-images.githubusercontent.com/2489685/32438266-bfcadec2-c2e1-11e7-9961-8fe5e2ecb4eb.jpg)

ED: this looks a separate issue then, I've moved to pRMT RADAR-cns/radar-prmt-android#53

**Comment by sboettcher** [comment]
Yep we have had the same issue before. I always saw it as an UDOO issue, but could not confirm its source yet.

**Comment by sboettcher** [comment]
Closing as deprecated
